source 'https://github.com/CocoaPods/Specs.git'  # 官方库

def shared_pods
    pod 'FRLoggerKit'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'ReactiveObjC', '~> 3.0.0'
end

target :'FRNetworkingWithRACKit' do
    platform :ios, '8.0'
    use_frameworks!
    shared_pods
end
